name: Deploy Astro site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "."

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Setup Node.js with Yarn
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: yarn
          cache-dependency-path: ${{ env.BUILD_PATH }}/yarn.lock

      # Step 3: Setup GitHub Pages
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5

      # Step 4: Install dependencies with Yarn
      - name: Install dependencies
        run: yarn install
        working-directory: ${{ env.BUILD_PATH }}

      # Step 5: Build the Astro site
      - name: Build with Astro
        run: yarn run build
        working-directory: ${{ env.BUILD_PATH }}

      # Step 6: Upload the build artifact
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.BUILD_PATH }}/dist

  deploy:
    environment:
      name: github-pages
      url: "https://harsh-m-patil.github.io"
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      # Step 7: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
